services:
  bot:
    image: ghcr.io/kapparina/ticketsplease:${IMAGE_TAG:-main}
    restart: unless-stopped
    environment:
      - TicketsPleaseBotToken=${TicketsPleaseBotToken}
    volumes:
      - ./config.toml:/config/config.toml:ro
    command: -config=/config/config.toml --sync-commands=true
    networks:
      - bot

networks:
  bot:
    name: bot
