services:
  bot:
    image: ghcr.io/kapparina/ticketsplease:main
    restart: unless-stopped
    environment:
      - TicketsPleaseBotToken=${TicketsPleaseBotToken}
    volumes:
      - ./config.toml:/var/lib/config.toml
    command: -config=/var/lib/config.toml --sync-commands=true
    networks:
      - bot

networks:
  bot:
    name: bot
